---
- hosts: pi
  remote_user: pi

  vars:
    root_path: /home/pi/mesi-io
    app_path: "{{ root_path }}/clipboard-service"
    container_name: mesi-io-clipboard-service

  tasks:

    - name: stop app
      shell: (docker kill {{ container_name }} || /bin/true) && (docker rm {{ container_name }} || /bin/true)

    - name: clean
      shell: find {{ app_path }} -type f ! -name 'log*' -delete || /bin/true

    - name: create directory
      file:
        path: "{{ app_path }}"
        state: directory
        mode: 0740

    - name: copy and extract app
      unarchive:
        src: clipboard-service.zip
        dest: "{{ app_path }}"
        mode: 0500

    - name: build app
      shell: docker build -t mesi/clipboard-service {{ app_path }}
    
    - name: run app
      shell: docker run -p 14100:5000 -v {{ app_path }}/logs:/app/logs -e MESI_IO_CLIPBOARD_SERVICE_ConnectionStrings__ClipboardDb -e MESI_IO_CLIPBOARD_SERVICE_OAuth__Authority --name {{ container_name }} -d mesi/clipboard-service
