version: '3.7'

services:

  mesi-io-clipboard-service:
    image: mesi/clipboard-service
    container_name: mesi-io-clipboard-service

    ports:
      - 14100:5000
      
    volumes:
      - ./logs:/app/logs

    environment:
      - MESI_IO_CLIPBOARD_SERVICE_ConnectionStrings__ClipboardDb
      - MESI_IO_CLIPBOARD_SERVICE_OAuth__Authority

    healthcheck:
      test: curl -f http://localhost:5000/heartbeat || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 1m