version: '3.7'

services:

  mesi-io-clipboard-service:
    image: mesi/clipboard-service
    container_name: clipboard-service

    ports:
      - 30001:5000
      
    volumes:
      - ./logs:/app/logs

    healthcheck:
      test: curl -f http://localhost:5000/heartbeat || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 1m